apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnf1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webnf
  template:
    metadata:
      labels:
        app: webnf
    spec:
      containers:
      - name: webnf1
        image: webnf1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webnf1-service
spec:
  type: NodePort
  selector:
    app: webnf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30420
