apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpf2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpf
  template:
    metadata:
      labels:
        app: webpf
    spec:
      containers:
      - name: webpf2
        image: webpf2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webpf2-service
spec:
  type: NodePort
  selector:
    app: webpf
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30421
