apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpf1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpf
  template:
    metadata:
      labels:
        app: webpf
    spec:
      containers:
      - name: webpf1
        image: webpf1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webpf1-service
spec:
  type: NodePort
  selector:
    app: webpf
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30420
